### ISSUE TITLE
Filters are not supported in code blocks

### ISSUE THREAD

**Issue by Alex-PK** [Keats/tera#150]
Apparently filters are not supported in code blocks. This is what I tried:

```
{% for element in list | reverse %}
```

I am getting this:

```
thread '<unnamed>' panicked at 'no pattern matched in _content; failed at [for_tag, identifier, identifier_with_filter, ...]', tera-0.8.1/src/parser.rs:212
```

I don't know nom enough to understand what's going on there, sorry. :)

I don't know if this could be considered a bug or a feature request, but it would be extremely useful in many situations, like `{% if name | lower == "alex" %}` or `{% if abstarct | wordcount | length > 30 %}.

Thanks.

**Comment by Keats** [comment]
So the filter on the forloop object can be added quite easily I believe.

For the `if` though, it's similar to #139. On a basic level it seems ok but if i write `{% if 1 + some_int | round > 10 %}`, it's not obvious what is the precedence is. Is it `1 + round(some_int)` or `round(1 + some_int)`? Both can be thought as correct.

The solution would be to add parenthesis to expressions in Tera so we can do `{% if (1 + some_int) | round > 10 %}` and `{% if 1 + (some_int | round) > 10 %}` but that's a bigger chunk of work.

I will probably do the `for` filters next week, unless you want to do it :) It uses pest, not nom so it's very easy to read/modify

**Comment by Keats** [comment]
Hmm @Alex-PK The `for` loop already supports filters on the latest after checking it.
I think the error here is complaining about the missing endfor?

If i add a test like:
```
    #[test]
    fn test_for_tag_with_filter2() {
        let mut parser = Rdp::new(StringInput::new("{% for element in list | reverse %}"));
        assert!(parser.for_tag());
        assert!(parser.end());
    }
```
it does pass.

Can you submit a PR with a failing test?

**Comment by Alex-PK** [comment]
While reading tera's code I found in the grammar that it should be supported, so I didn't really know how to proceed from there.
My case was a bit different. I had something like:

```
{% for page in site.sitemap.folders.post.pages %}

 ...
{% endfor %}
```

and just appended a `|reverse`. Maybe it has something to do with nesting. I'll see if I am able to build a test case.

Thanks.

**Comment by phil-opp** [comment]
I'm hitting this too when I try to reverse the `pages` array in `index.html` of my gutenberg project:

```html
{% for page in pages | reverse %}
    <article>
        <h1 class="post-title"><a href="{{ page.path }}">{{ page.title }}</a></h1>
        {{ page.summary | safe }}
    </article>
{% endfor %}
```

The following panic occurs:

```
thread 'main' panicked at 'no pattern matched in _content;
  failed at [for_tag, identifier, identifier_with_filter, ...]',
  .cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.9.0/src/parser.rs:212
```

<details>
<summary>Backtrace (optimized)</summary>

```
thread 'main' panicked at 'no pattern matched in _content; failed at [for_tag, identifier, identifier_with_filter, ...]', .cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.9.0/src/parser.rs:212
stack backtrace:
   0:     0x56157cc19133 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h0c49f46a3545f908
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x56157cc14f44 - std::sys_common::backtrace::_print::hcef39a9816714c4c
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x56157cc1dc37 - std::panicking::default_hook::{{closure}}::h7c3c94835e02f846
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x56157cc1d7bb - std::panicking::default_hook::h0bf7bc3112fb107d
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x56157cc1e10b - std::panicking::rust_panic_with_hook::ha27630c950090fec
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x56157cc1dfe4 - std::panicking::begin_panic::heb97fa3158b71158
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x56157cc1df19 - std::panicking::begin_panic_fmt::h8144403278d84748
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x56157ca9d540 - <tera::parser::Rdp<T>>::_content::h7b06b105ec20755a
   8:     0x56157ca99290 - <tera::parser::Rdp<T>>::_template::h3e9841ad45d4d71b
   9:     0x56157ca992a0 - <tera::parser::Rdp<T>>::_template::h3e9841ad45d4d71b
  10:     0x56157ca9bb57 - <tera::parser::Rdp<T>>::_content::h7b06b105ec20755a
  11:     0x56157ca99040 - <tera::parser::Rdp<T>>::_template::h3e9841ad45d4d71b
  12:     0x56157ca99050 - <tera::parser::Rdp<T>>::_template::h3e9841ad45d4d71b
  13:     0x56157ca99050 - <tera::parser::Rdp<T>>::_template::h3e9841ad45d4d71b
  14:     0x56157ca99050 - <tera::parser::Rdp<T>>::_template::h3e9841ad45d4d71b
  15:     0x56157ca98c84 - <tera::parser::Rdp<T>>::_template::h3e9841ad45d4d71b
  16:     0x56157ca5a64d - tera::template::Template::new::he0dcfe3f9c36b8f9
  17:     0x56157ca5ede0 - tera::tera::Tera::load_from_glob::hae5e10403cf010b2
  18:     0x56157ca5da5f - tera::tera::Tera::new::hd02ba1857763fe7a
  19:     0x56157c8fb555 - gutenberg::site::Site::new::ha8ad3246667aa465
  20:     0x56157c8fd173 - gutenberg::cmd::serve::serve::h8271e68a5b13df28
  21:     0x56157c9080cc - gutenberg::main::h430a5497c38b8169
  22:     0x56157cc1de05 - std::panicking::try::do_call::h689a21caeeef92aa
                               at /checkout/src/libcore/ops.rs:2606
                               at /checkout/src/libstd/panicking.rs:454
  23:     0x56157cc2509a - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  24:     0x56157cc1e8aa - std::rt::lang_start::hf63d494cb7dd034c
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:57
  25:     0x7fae07e7482f - __libc_start_main
  26:     0x56157c8b6e08 - _start
  27:                0x0 - <unknown>
```

</details>

**Comment by Keats** [comment]
I found the issue, I'll fix it tomorrow. Thanks!

**Comment by Keats** [comment]
#164 should do the trick! I'll merge and release in a bit

**Comment by Keats** [comment]
I pushed 0.10 to fix that and pushed the new version of Tera in gutenberg in master

**Comment by phil-opp** [comment]
Thanks, it works now.
