### ISSUE TITLE
Tera::new crashes with ./path/* parameter

### ISSUE THREAD

**Issue by huin** [Keats/tera#193]
Examples:

https://github.com/huin/rust-issues/blob/master/tera-glob-prefix/src/lib.rs

```
$ RUST_BACKTRACE=1 cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/tera_glob_prefix-49349ca226277628

running 2 tests
test tests::loads_templates_with_relative ... ok
test tests::loads_template_with_relative_dot_slash ... FAILED

failures:

---- tests::loads_template_with_relative_dot_slash stdout ----
	thread 'tests::loads_template_with_relative_dot_slash' panicked at 'called `Result::unwrap()` on an `Err` value: StripPrefixError(())', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:365
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: tera::tera::Tera::load_from_glob
             at /home/huin/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.10.8/src/tera.rs:98
  12: tera::tera::Tera::new
             at /home/huin/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-0.10.8/src/tera.rs:65
  13: tera_glob_prefix::tests::loads_template_with_relative_dot_slash
             at ./src/lib.rs:9
  14: <F as test::FnBox<T>>::call_box
             at /checkout/src/libtest/lib.rs:1368
             at /checkout/src/libcore/ops.rs:2626
             at /checkout/src/libtest/lib.rs:140
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  16: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libtest/lib.rs:1313
             at /checkout/src/libstd/panic.rs:296
             at /checkout/src/libstd/panicking.rs:454
  17: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  18: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/thread/mod.rs:360
             at /checkout/src/liballoc/boxed.rs:640
  19: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:650
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  20: start_thread
  21: __clone


failures:
    tests::loads_template_with_relative_dot_slash

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured

error: test failed, to rerun pass '--lib'
```

Having run this through a debugger, it appears that stripping the prefix results in Result::Err, because the given prefix contains the "./" component, but the file path being stripped does not.

**Comment by Keats** [comment]
Thanks! https://github.com/Keats/tera/commit/f2d3cb5ac4d612874235f606eadfadb1aab3d51e should fix that

**Comment by huin** [comment]
Thanks - I've added a comment there.

**Comment by Keats** [comment]
The fixed version is in master and will be published in the next version soon
