### ISSUE TITLE
Internal parsing error while compiling templates

### ISSUE THREAD

**Issue by 64** [Keats/tera#412]
Getting this very strange internal error when trying to compile templates:
```
    Finished dev [unoptimized + debuginfo] target(s) in 22.91s
     Running `target/debug/mordhub`
Starting server on 0.0.0.0:3000
thread 'actix-rt:worker:0' panicked at 'internal error: entered unreachable code: Invalid arg type for test test_arg', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:131:30
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.25/src/backtrace/libunwind.rs:97
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.25/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:197
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   9: tera::parser::parse_test_call
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:131
  10: tera::parser::parse_test
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:151
  11: tera::parser::parse_basic_expression
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:258
  12: tera::parser::parse_basic_expression::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:223
  13: pest::prec_climber::PrecClimber<R>::climb
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pest-2.1.1/src/prec_climber.rs:178
  14: tera::parser::parse_basic_expression
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:267
  15: tera::parser::parse_basic_expr_with_filters
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:280
16: tera::parser::parse_comparison_val
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:363
  17: tera::parser::parse_comparison_val::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:345
  18: pest::prec_climber::PrecClimber<R>::climb
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pest-2.1.1/src/prec_climber.rs:178
  19: tera::parser::parse_comparison_val
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:364
  20: tera::parser::parse_comparison_expression
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:390
  21: tera::parser::parse_comparison_expression::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:371
  22: pest::prec_climber::PrecClimber<R>::climb
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pest-2.1.1/src/prec_climber.rs:178
  23: tera::parser::parse_comparison_expression
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:393
  24: tera::parser::parse_logic_val
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:410
  25: tera::parser::parse_logic_expr
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:442
  26: tera::parser::parse_logic_expr::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:422
  27: pest::prec_climber::PrecClimber<R>::climb
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pest-2.1.1/src/prec_climber.rs:178
  28: tera::parser::parse_logic_expr
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:443
  29: tera::parser::parse_if
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:867
  30: tera::parser::parse_content
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:942
  31: tera::parser::parse
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/parser/mod.rs:1091
  32: tera::template::Template::new
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/template.rs:48
  33: tera::tera::Tera::add_file
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/tera.rs:183
  34: tera::tera::Tera::load_from_glob
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/tera.rs:149
  35: tera::tera::Tera::create
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/tera.rs:62
  36: tera::tera::Tera::new
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.0.0-beta.7/src/tera.rs:85
  37: mordhub::main::{{closure}}
             at src/main.rs:41
...
```

Might this be caused by the recent commit to src/parser/mod.rs#L131?

I'm using `tera 1.0.0-beta.7` as you can see.

**Comment by Keats** [comment]
Which version of Tera? Can you paste the template?

Il sab 1 giu 2019, 16:49 Matt Taylor <notifications@github.com> ha scritto:

**Comment by 64** [comment]
`{% if foo is sometest("bar") %}{% endif %}` This seems sufficient to trigger it. As mentioned, I'm using 1.0.0-beta 7.

**Comment by 64** [comment]
Seems like any test that takes an argument will trigger the error, e.g `divisibleby(2)`. Things like `defined` or `odd` don't.

**Comment by Keats** [comment]
Whoa thanks. I've pushed a commit fixing that but obviously that means there are no tests for template tests, I'll write some before pushing a release later tonight.

**Comment by Keats** [comment]
Published as beta 8, thanks for reporting!
