### ISSUE TITLE
if `start > end` then `slice` filter panicks

### ISSUE THREAD

**Issue by rootkea** [Keats/tera#702]
Hello!

```
{{ [1, "foo", 1, "true", "FOO", true, 2] | slice(start=4, end=2) }}
```

panick:
```
thread 'thread '<unnamed>thread '<unnamed>' panicked at 'slice index starts at 4 but ends at 2' panicked at 'slice index starts at 4 but ends at 2<unnamed>' panicked at '', thread 'slice index starts at 4 but ends at 2<unnamed>' panicked at 'slice index starts at 4 but ends at 2', /home/rootkea/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.15.0/src/builtins/filters/array.rs/home/rootkea/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.15.0/src/builtins/filters/array.rs:285:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
:285:8
', ', /home/rootkea/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.15.0/src/builtins/filters/array.rs:285:8
thread 'thread '<unnamed>' panicked at 'slice index starts at 4 but ends at 2', /home/rootkea/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.15.0/src/builtins/filters/array.rs:285:8
/home/rootkea/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.15.0/src/builtins/filters/array.rs:285:8
thread '<unnamed>' panicked at 'slice index starts at 4 but ends at 2thread '<unnamed>' panicked at 'slice index starts at 4 but ends at 2', /home/rootkea/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.15.0/src/builtins/filters/array.rs:285:8
thread '<unnamed>' panicked at 'slice index starts at 4 but ends at 2', /home/rootkea/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.15.0/src/builtins/filters/array.rs:285:8
thread '<unnamed>' panicked at 'slice index starts at 4 but ends at 2', /home/rootkea/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.15.0/src/builtins/filters/array.rs:285:8
<unnamed>', /home/rootkea/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.15.0/src/builtins/filters/array.rs:285:8
' panicked at 'thread 'slice index starts at 4 but ends at 2', /home/rootkea/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.15.0/src/builtins/filters/array.rs:285:8
<unnamed>' panicked at 'slice index starts at 4 but ends at 2', /home/rootkea/.cargo/registry/src/github.com-1ecc6299db9ec823/tera-1.15.0/src/builtins/filters/array.rs:285:8
```

Interestingly, if `start == end` empty array is returned. So what to do when `start > end`?
1. Return empty array OR
2. throw error

**Comment by rootkea** [comment]
I think return an empty array so as to be consistent since following doesn't panick and simply returns empty array even if `start > end`:
```
{{ [1, "foo", 1, "true", "FOO", true, 2] | slice(start=8, end=2) }}
```

**Comment by rootkea** [comment]
Preparing a PR now...
